name: Build & Pubish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Tool
      run: dotnet restore
    - name: Build
      run: dotnet build -c Debug --no-restore
    - name: Test
      run: dotnet test -c Debug --no-build

  build:
    name: Build project and pack
    needs: test
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${GITHUB_REF/refs\/tags\/v/}

    - name: Packaging
      run: dotnet pack VRChatAPI/ --configuration Release --no-build --output packages -p:PackageVersion=${GITHUB_REF/refs\/tags\/v/}

    - name: upload packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: packages

  upload:
    name: Publish to NuGet repos
    needs: build
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore
    
    - name: download nupkgs
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: packages
    
    - name: ls 
      run: ls nupkgs

    - name: Nuget Push
      run:  dotnet nuget push packages\*.nupkg -k ${{ secrets.NUGET_API_KEY }}  --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: AddGithubSource
      run: dotnet nuget add source --username mueru --password ${{secrets.GITHUB_TOKEN}} --name github https://nuget.pkg.github.com/mueru/index.json

    - name: PushGithub
      run: dotnet nuget push packages\*.nupkg --source github --skip-duplicate
